import { WordDefinitionSchema, type WordDefinition } from "./schemas";

const words = [
  {
    id: "evidence",
    word: "evidence",
    partOfSpeech: "noun",
    meaningZh: "证据；证明",
    exampleEn: "The detective found evidence beside the locked cabinet.",
    exampleZh: "侦探在上锁的柜子旁发现了证据。",
    acceptedSpellings: ["evidence"],
    confusionSet: ["evident", "testimony"],
  },
  {
    id: "suspect",
    word: "suspect",
    partOfSpeech: "noun",
    meaningZh: "嫌疑人",
    exampleEn: "Every suspect had access to the archive.",
    exampleZh: "每名嫌疑人都有进入档案室的权限。",
    acceptedSpellings: ["suspect"],
    confusionSet: ["witness", "motive"],
  },
  {
    id: "witness",
    word: "witness",
    partOfSpeech: "noun",
    meaningZh: "目击者；证人",
    exampleEn: "The witness remembered a silver umbrella.",
    exampleZh: "目击者记得一把银色雨伞。",
    acceptedSpellings: ["witness"],
    confusionSet: ["suspect", "testimony"],
  },
  {
    id: "conceal",
    word: "conceal",
    partOfSpeech: "verb",
    meaningZh: "隐藏；隐瞒",
    exampleEn: "Heavy curtains concealed the narrow passage.",
    exampleZh: "厚重的窗帘遮住了狭窄的通道。",
    acceptedSpellings: ["conceal"],
    confusionSet: ["reveal", "deceive"],
  },
  {
    id: "reveal",
    word: "reveal",
    partOfSpeech: "verb",
    meaningZh: "揭示；透露",
    exampleEn: "The final page may reveal who changed the record.",
    exampleZh: "最后一页可能会揭示是谁篡改了记录。",
    acceptedSpellings: ["reveal"],
    confusionSet: ["conceal", "verify"],
  },
  {
    id: "verify",
    word: "verify",
    partOfSpeech: "verb",
    meaningZh: "核实；验证",
    exampleEn: "We must verify the guard's account before midnight.",
    exampleZh: "我们必须在午夜前核实守卫的说法。",
    acceptedSpellings: ["verify"],
    confusionSet: ["reveal", "interpret"],
  },
  {
    id: "contradict",
    word: "contradict",
    partOfSpeech: "verb",
    meaningZh: "反驳；与……矛盾",
    exampleEn: "The footprints contradict his version of events.",
    exampleZh: "脚印与他对事件的说法相矛盾。",
    acceptedSpellings: ["contradict"],
    confusionSet: ["correspond", "testimony"],
  },
  {
    id: "testimony",
    word: "testimony",
    partOfSpeech: "noun",
    meaningZh: "证词；证言",
    exampleEn: "Her testimony placed the courier near the gate.",
    exampleZh: "她的证词表明信使当时在城门附近。",
    acceptedSpellings: ["testimony"],
    confusionSet: ["evidence", "witness"],
  },
  {
    id: "credible",
    word: "credible",
    partOfSpeech: "adjective",
    meaningZh: "可信的；可靠的",
    exampleEn: "Only one explanation sounded credible.",
    exampleZh: "只有一种解释听起来可信。",
    acceptedSpellings: ["credible"],
    confusionSet: ["decisive", "evident"],
  },
  {
    id: "motive",
    word: "motive",
    partOfSpeech: "noun",
    meaningZh: "动机；目的",
    exampleEn: "The missing payment gave the clerk a motive.",
    exampleZh: "失踪的款项给了那名职员作案动机。",
    acceptedSpellings: ["motive"],
    confusionSet: ["suspect", "alibi"],
  },
  {
    id: "alibi",
    word: "alibi",
    partOfSpeech: "noun",
    meaningZh: "不在场证明",
    exampleEn: "A dated receipt supported her alibi.",
    exampleZh: "一张标有日期的收据支持了她的不在场证明。",
    acceptedSpellings: ["alibi"],
    confusionSet: ["motive", "testimony"],
  },
  {
    id: "infer",
    word: "infer",
    partOfSpeech: "verb",
    meaningZh: "推断；推论",
    exampleEn: "We can infer the route from the mud on his shoes.",
    exampleZh: "我们可以从他鞋上的泥推断出路线。",
    acceptedSpellings: ["infer"],
    confusionSet: ["interpret", "imply"],
  },
  {
    id: "acquire",
    word: "acquire",
    partOfSpeech: "verb",
    meaningZh: "获得；取得",
    exampleEn: "The collector tried to acquire the rare formula.",
    exampleZh: "收藏家试图获得那份稀有配方。",
    acceptedSpellings: ["acquire"],
    confusionSet: ["accuse", "require"],
  },
  {
    id: "prescription",
    word: "prescription",
    partOfSpeech: "noun",
    meaningZh: "处方；药方",
    exampleEn: "The prescription was written in unfamiliar ink.",
    exampleZh: "这张处方是用陌生的墨水写成的。",
    acceptedSpellings: ["prescription"],
    confusionSet: ["remedy", "diagnose"],
  },
  {
    id: "toxic",
    word: "toxic",
    partOfSpeech: "adjective",
    meaningZh: "有毒的；有害的",
    exampleEn: "The laboratory report described the powder as toxic.",
    exampleZh: "实验室报告称这种粉末有毒。",
    acceptedSpellings: ["toxic"],
    confusionSet: ["symptom", "remedy"],
  },
  {
    id: "remedy",
    word: "remedy",
    partOfSpeech: "noun",
    meaningZh: "治疗方法；补救措施",
    exampleEn: "The old remedy contained three common herbs.",
    exampleZh: "这种古老药方含有三种常见草药。",
    acceptedSpellings: ["remedy"],
    confusionSet: ["prescription", "symptom"],
  },
  {
    id: "diagnose",
    word: "diagnose",
    partOfSpeech: "verb",
    meaningZh: "诊断；判断问题",
    exampleEn: "The physician refused to diagnose the patient without evidence.",
    exampleZh: "医师拒绝在没有证据的情况下诊断病人。",
    acceptedSpellings: ["diagnose"],
    confusionSet: ["diagnosis", "prescription"],
  },
  {
    id: "symptom",
    word: "symptom",
    partOfSpeech: "noun",
    meaningZh: "症状；征兆",
    exampleEn: "Dizziness was the first symptom mentioned in the diary.",
    exampleZh: "眩晕是日记中提到的第一个症状。",
    acceptedSpellings: ["symptom"],
    confusionSet: ["symbol", "remedy"],
  },
  {
    id: "cipher",
    word: "cipher",
    partOfSpeech: "noun",
    meaningZh: "密码；暗号",
    exampleEn: "A simple cipher protected the message.",
    exampleZh: "一种简单的密码保护着这条消息。",
    acceptedSpellings: ["cipher", "cypher"],
    confusionSet: ["code", "interpret"],
  },
  {
    id: "anonymous",
    word: "anonymous",
    partOfSpeech: "adjective",
    meaningZh: "匿名的；身份不明的",
    exampleEn: "An anonymous caller warned us about the tunnel.",
    exampleZh: "一名匿名来电者警告我们注意隧道。",
    acceptedSpellings: ["anonymous"],
    confusionSet: ["unknown", "conceal"],
  },
  {
    id: "correspond",
    word: "correspond",
    partOfSpeech: "verb",
    meaningZh: "相符合；通信",
    exampleEn: "The marks correspond to stations on the old map.",
    exampleZh: "这些标记与旧地图上的车站相对应。",
    acceptedSpellings: ["correspond"],
    confusionSet: ["contradict", "transmit"],
  },
  {
    id: "interpret",
    word: "interpret",
    partOfSpeech: "verb",
    meaningZh: "解释；理解",
    exampleEn: "She interpreted the pause as a warning.",
    exampleZh: "她把那次停顿理解为警告。",
    acceptedSpellings: ["interpret"],
    confusionSet: ["infer", "translate"],
  },
  {
    id: "transmit",
    word: "transmit",
    partOfSpeech: "verb",
    meaningZh: "传送；播送",
    exampleEn: "The device can transmit a signal through concrete walls.",
    exampleZh: "该设备可以穿过混凝土墙传送信号。",
    acceptedSpellings: ["transmit"],
    confusionSet: ["intercept", "correspond"],
  },
  {
    id: "intercept",
    word: "intercept",
    partOfSpeech: "verb",
    meaningZh: "截获；拦截",
    exampleEn: "The operator managed to intercept the hidden broadcast.",
    exampleZh: "操作员设法截获了隐藏广播。",
    acceptedSpellings: ["intercept"],
    confusionSet: ["transmit", "interrupt"],
  },
  {
    id: "banquet",
    word: "banquet",
    partOfSpeech: "noun",
    meaningZh: "宴会；盛宴",
    exampleEn: "The minister left the banquet before the final course.",
    exampleZh: "大臣在最后一道菜上桌前离开了宴会。",
    acceptedSpellings: ["banquet"],
    confusionSet: ["etiquette", "witness"],
  },
  {
    id: "etiquette",
    word: "etiquette",
    partOfSpeech: "noun",
    meaningZh: "礼仪；礼节",
    exampleEn: "Court etiquette required every guest to bow twice.",
    exampleZh: "宫廷礼仪要求每位宾客行礼两次。",
    acceptedSpellings: ["etiquette"],
    confusionSet: ["banquet", "discreet"],
  },
  {
    id: "discreet",
    word: "discreet",
    partOfSpeech: "adjective",
    meaningZh: "谨慎的；不引人注意的",
    exampleEn: "A discreet inquiry would avoid alarming the suspect.",
    exampleZh: "谨慎调查可以避免惊动嫌疑人。",
    acceptedSpellings: ["discreet"],
    confusionSet: ["discrete", "conceal"],
  },
  {
    id: "persuade",
    word: "persuade",
    partOfSpeech: "verb",
    meaningZh: "说服；劝服",
    exampleEn: "We need to persuade the servant to open the side gate.",
    exampleZh: "我们需要说服仆人打开侧门。",
    acceptedSpellings: ["persuade"],
    confusionSet: ["coerce", "accuse"],
  },
  {
    id: "postpone",
    word: "postpone",
    partOfSpeech: "verb",
    meaningZh: "推迟；延期",
    exampleEn: "The captain agreed to postpone the inspection.",
    exampleZh: "队长同意推迟检查。",
    acceptedSpellings: ["postpone"],
    confusionSet: ["delay", "resolve"],
  },
  {
    id: "accuse",
    word: "accuse",
    partOfSpeech: "verb",
    meaningZh: "指控；控告",
    exampleEn: "Do not accuse anyone until the timeline is complete.",
    exampleZh: "在时间线完整之前不要指控任何人。",
    acceptedSpellings: ["accuse"],
    confusionSet: ["acquire", "suspect"],
  },
  {
    id: "confess",
    word: "confess",
    partOfSpeech: "verb",
    meaningZh: "坦白；承认",
    exampleEn: "The courier refused to confess to changing the seal.",
    exampleZh: "信使拒绝承认更换了封印。",
    acceptedSpellings: ["confess"],
    confusionSet: ["conceal", "testimony"],
  },
  {
    id: "coerce",
    word: "coerce",
    partOfSpeech: "verb",
    meaningZh: "强迫；胁迫",
    exampleEn: "Someone tried to coerce the witness into silence.",
    exampleZh: "有人试图胁迫证人保持沉默。",
    acceptedSpellings: ["coerce"],
    confusionSet: ["persuade", "accuse"],
  },
  {
    id: "reluctant",
    word: "reluctant",
    partOfSpeech: "adjective",
    meaningZh: "不情愿的；勉强的",
    exampleEn: "The reluctant guard eventually showed us the register.",
    exampleZh: "那名不情愿的守卫最终给我们看了登记簿。",
    acceptedSpellings: ["reluctant"],
    confusionSet: ["innocent", "credible"],
  },
  {
    id: "deceive",
    word: "deceive",
    partOfSpeech: "verb",
    meaningZh: "欺骗；蒙蔽",
    exampleEn: "The edited recording was designed to deceive listeners.",
    exampleZh: "剪辑过的录音旨在欺骗听众。",
    acceptedSpellings: ["deceive"],
    confusionSet: ["conceal", "betray"],
  },
  {
    id: "betray",
    word: "betray",
    partOfSpeech: "verb",
    meaningZh: "背叛；暴露",
    exampleEn: "A nervous gesture may betray what he knows.",
    exampleZh: "一个紧张的动作可能会暴露他知道的事情。",
    acceptedSpellings: ["betray"],
    confusionSet: ["deceive", "reveal"],
  },
  {
    id: "innocent",
    word: "innocent",
    partOfSpeech: "adjective",
    meaningZh: "无罪的；清白的",
    exampleEn: "The missing key may prove that she is innocent.",
    exampleZh: "失踪的钥匙可能证明她是清白的。",
    acceptedSpellings: ["innocent"],
    confusionSet: ["guilty", "suspect"],
  },
  {
    id: "verdict",
    word: "verdict",
    partOfSpeech: "noun",
    meaningZh: "裁决；判定",
    exampleEn: "The council will announce its verdict at dawn.",
    exampleZh: "委员会将在黎明时宣布裁决。",
    acceptedSpellings: ["verdict"],
    confusionSet: ["justice", "consequence"],
  },
  {
    id: "justice",
    word: "justice",
    partOfSpeech: "noun",
    meaningZh: "正义；公正",
    exampleEn: "Justice depends on evidence rather than rumours.",
    exampleZh: "公正取决于证据，而不是流言。",
    acceptedSpellings: ["justice"],
    confusionSet: ["verdict", "accountable"],
  },
  {
    id: "decisive",
    word: "decisive",
    partOfSpeech: "adjective",
    meaningZh: "决定性的；果断的",
    exampleEn: "The timestamp became the decisive clue.",
    exampleZh: "时间戳成为了决定性线索。",
    acceptedSpellings: ["decisive"],
    confusionSet: ["credible", "evident"],
  },
  {
    id: "consequence",
    word: "consequence",
    partOfSpeech: "noun",
    meaningZh: "后果；结果",
    exampleEn: "A false accusation can have a serious consequence.",
    exampleZh: "错误指控可能造成严重后果。",
    acceptedSpellings: ["consequence"],
    confusionSet: ["outcome", "verdict"],
  },
  {
    id: "accountable",
    word: "accountable",
    partOfSpeech: "adjective",
    meaningZh: "负有责任的；应作解释的",
    exampleEn: "The director is accountable for the missing files.",
    exampleZh: "主管应对丢失的文件负责。",
    acceptedSpellings: ["accountable"],
    confusionSet: ["responsible", "credible"],
  },
  {
    id: "resolve",
    word: "resolve",
    partOfSpeech: "verb",
    meaningZh: "解决；下定决心",
    exampleEn: "One honest statement could resolve the entire case.",
    exampleZh: "一句诚实的陈述就能解决整个案件。",
    acceptedSpellings: ["resolve"],
    confusionSet: ["solve", "postpone"],
  },
] satisfies WordDefinition[];

export const sharedCurriculum = WordDefinitionSchema.array().length(42).parse(words);

export const wordById = new Map(sharedCurriculum.map((word) => [word.id, word]));

export const curriculumWordGroups = Array.from({ length: 7 }, (_, index) =>
  sharedCurriculum.slice(index * 6, index * 6 + 6).map((word) => word.id),
);
